name: Promote GPT Patch

on:
  push:
    paths:
      - '.patches/*.diff'

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.name "chatgpt-bot"
          git config --global user.email "chatgpt-bot@users.noreply.github.com"

      - name: Detect triggered patch
        id: detect
        run: |
          PATCH_NAME=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '^.patches/' | head -n 1 | xargs basename)
          echo "TRIGGERED_PATCH=$PATCH_NAME" >> $GITHUB_ENV
          echo "🕵️ Detected patch: $PATCH_NAME"

      - name: Promote patch to feature branch
        run: bash scripts/create_pr_from_patch.sh
        env:
          TRIGGERED_PATCH: ${{ env.TRIGGERED_PATCH }}
